name: chat-system

services:
  chats-worker:
    build: .
    command: rails chats_worker
    volumes:
      - .:/chat-system
    restart: on-failure
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - elasticsearch
    environment:
      RABBITMQ_HOST: rabbitmq
      REDIS_URL: redis://redis:6379
      MYSQL_HOST: mysql
      MYSQL_DATABASE_PASSWORD: my-secret-password
      ELASTICSEARCH_URL: http://elasticsearch:9200

  messages-worker:
    build: .
    command: rails messages_worker
    volumes:
      - .:/chat-system
    restart: on-failure
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - elasticsearch
    environment:
      RABBITMQ_HOST: rabbitmq
      REDIS_URL: redis://redis:6379
      MYSQL_HOST: mysql
      MYSQL_DATABASE_PASSWORD: my-secret-password
      ELASTICSEARCH_URL: http://elasticsearch:9200

  web:
    build: .
    command: /bin/sh -c "cron -f & bin/rails server -b 0.0.0.0 & bundle exec whenever --update-crontab --set environment=development & wait"
    volumes:
      - .:/chat-system
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - elasticsearch
    environment:
      RABBITMQ_HOST: rabbitmq
      REDIS_URL: redis://redis:6379
      MYSQL_HOST: mysql
      MYSQL_DATABASE_PASSWORD: my-secret-password
      ELASTICSEARCH_URL: http://elasticsearch:9200

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password # Replace with a strong password
      MYSQL_DATABASE: chat-system # Replace with your desired database name
    volumes:
      - mysql-data:/var/lib/mysql # Persistent volume for data
    ports:
      - 3306:3306 # Expose MySQL port

  redis:
    image: redis
    volumes:
      - redis-data:/data # Persistent volume for data
    ports:
      - 6379:6379 # Expose Redis port

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      discovery.type: single-node # Configure as a single-node cluster
      xpack.security.enabled: false # Disable X-Pack security
      xpack.security.http.ssl.enabled: false
      xpack.security.authc.api_key.enabled: false
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch # Persistent volume for data
    ports:
      - 9200:9200 # Expose Elasticsearch port
      - 9300:9300 # Expose Elasticsearch transport port

  rabbitmq:
    image: rabbitmq:3.13-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq # Persistent volume for data
    ports:
      - 5672:5672 # Expose RabbitMQ port
      - 15672:15672 # Expose RabbitMQ management port

volumes:
  mysql-data: # Define persistent volume for MySQL data
  redis-data: # Define persistent volume for Redis data
  elasticsearch-data: # Define persistent volume for Elasticsearch data
  rabbitmq-data: # Define persistent volume for RabbitMQ data
